### PR TITLE
Use HTML5 audio instead of Web Audio API

### PR DESCRIPTION
**Pull request by Mesoptier**
@villermen, can you test this on the production server?
If it works, it was an _incredibly_ easy solution for https://github.com/villermen/soundboard/issues/52.

### CODE REVIEW

**Comment by villermen** [comment]
I've used the same approach, but with Content-Length. Let's see how this one will behave.

**Comment by villermen** [comment]
Also, while I'm at it. What's with the modal appearing on load, and then instantly fading out? Is it debug code? Noticed this coming with the latest pull data.

**Comment by villermen** [comment]
The header seemed to fix it. You will receive all my internets for today. Too bad it will be over in 3 minutes...

**Comment by Mesoptier** [comment]
I believe `Content-Length` header is automatically managed by Slim already.

Does the modal also appear and instantly fade out after a refresh? I have noticed it when LiveReload reloads the page, but when I pressed <kbd>F5</kbd> it didn't.

All the internets for <s>3</s> <s>1</s> no more minutes!

**Comment by villermen** [comment]
It happens on load and refresh for me. I'm not using LiveReload.

**Comment by villermen** [comment]
I'm making an issue for this now btw.

**Pull request merged**
