### PR TITLE
Google vertalen plz

### PR DESCRIPTION
**Pull request by cascer1**

### CODE REVIEW

**Comment by villermen** [comment]
@Mesoptier This needs a code review and guideline specification rationalization implementation check. Agreed?

**Comment by Mesoptier** [comment]
@cascer1 Please reply with extensive reasoning for this pull request. If you do not comply within 42 minutes I will be forced to close this pull request.

<sub>Maar serieus, laat die Zweden toch met rust.</sub>

**Comment by villermen** [comment]
> **VILLERBOT** has detected a possible soundbyte reference and has commented said soundbyte for your hearing pleasure.

https://viller.men/soundboard/4c3c01c7

**Comment by Mesoptier** [comment]
4 hours > 42 minutes

https://viller.men/soundboard/be66d382

**Pull request closed without merging**
